# Generated by Django 6.0 on 2025-12-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(verbose_name='Analysis Result JSON')),
                ('summary_text', models.TextField(blank=True, verbose_name='Summary Text')),
                ('success_probability', models.IntegerField(default=0, verbose_name='Success Probability')),
                ('is_mock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
