# Generated by Django 6.0 on 2025-12-27 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('cases', '0003_caseupdate_caseupdatefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Result', 'verbose_name_plural': 'Analysis Results'},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='schema_version',
            field=models.CharField(default='2.0', max_length=10, verbose_name='Schema Version'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='source',
            field=models.CharField(choices=[('ai-engine', 'AI Engine'), ('experimental-mock', 'Experimental Mock')], default='experimental-mock', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cases.case'),
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('USER_MANUAL', 'User Manual'), ('SYSTEM_EVENT', 'System Event')], max_length=20, verbose_name='Trigger Type')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='analysis.analysisresult')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='cases.case')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Request',
                'verbose_name_plural': 'Analysis Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
