# Generated by Django 6.0 on 2025-12-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysisresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='derived_from_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='derived_from_event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='schema_version',
            field=models.CharField(default='3.0', max_length=10, verbose_name='Schema Version'),
        ),
    ]
