# Generated by Django 6.0 on 2025-12-27 08:05

import cases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('AUDIO', 'Audio Recording'), ('EVENT_NOTE', 'Event Note'), ('COURT_RULING', 'Court Ruling')], max_length=20, verbose_name='Update Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case')),
            ],
            options={
                'verbose_name': 'Case Update',
                'verbose_name_plural': 'Case Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cases.models.case_update_file_path, verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cases.caseupdate')),
            ],
        ),
    ]
