# Generated by Django 6.0 on 2025-12-27 08:29

import cases.models
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseupdate_caseupdatefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseupdatefile',
            name='update',
        ),
        migrations.CreateModel(
            name='CaseDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_id', models.CharField(max_length=100)),
                ('option_id', models.CharField(max_length=100)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('court_verdict', 'Court Verdict'), ('hearing_outcome', 'Hearing Outcome'), ('evidence_submitted', 'Evidence Submitted'), ('note', 'Note'), ('settlement', 'Settlement'), ('other', 'Other')], max_length=50, verbose_name='Event Type')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('timestamp', models.DateTimeField(default=django.db.models.functions.datetime.Now, verbose_name='Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Event',
                'verbose_name_plural': 'Case Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseEventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cases.models.case_event_file_path, verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.caseevent')),
            ],
        ),
        migrations.DeleteModel(
            name='CaseUpdate',
        ),
        migrations.DeleteModel(
            name='CaseUpdateFile',
        ),
    ]
